version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./project.env
    volumes:
      - postgres:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'   
    volumes: 
      - cache:/data
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - cache
volumes:
  postgres:
  cache:
    driver: local