services:
  postgres:
    image: postgres
    container_name: EtsyPostgres
    ports:
      - 6500:5432
    env_file:
      - ./project.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: