name: CI/CD for EtsyShop_Scraper

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
<<<<<<< HEAD
        go-version: '1.21'
=======
        go-version: '1.21-alpine'
>>>>>>> dac65546c5c11222fb680035f0c9e9276e22728a
    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run Linter
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Run Tests
      run: |
        go test ./... -v
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest .
        docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest
